dist: focal
language: node_js
node_js:
   - "node" # Latest node version
   - "lts/*" # Latest LTS version
   - "16"
   - "12"

before_install: npm i -g npm@8.5.5

script:
   - node --version
   - npm --version
   - npm run standards
   - commitlint-travis
