language: node_js
node_js:
   - "node" # Latest node version
   - "lts/*" # Latest LTS version
   - "12"
   - "10"

before_install: npm i -g npm@6.14.12

script:
   - node --version
   - npm --version
   - npm run standards
   - commitlint-travis
